### ISSUE TITLE
There is no nice way to blacklist for all caps patterns

### ISSUE THREAD

**Issue by Yalfoosh** [nyu8/flarum-email-filter#1]
Currently, the mail filter works as intended - it filters using regular expressions and it does it well. However, users may sometimes try to evade blacklists because the extension correctly assumes that the pattern written in some casing corresponds exactly to that casing when validations. This is a fine assumption but might not be ideal because Flarum already considers e-mails case-insensitive, meaning something like `ab12345@mail.com` is the same as `AB12345@mail.com`. The extension, however, doesn't assume this, and if you have a deleted users and a blacklist filter in place, they can bypass it by changing the filter.

For whitelisting purposes, this is fine, because users can just type in a correct mail and that is that. However, for blacklisting purposes, it might be smarter to enable at least a flag which enables case insensitive matching - meaning that before mail validation, if such flag is set, the email to be checked is lowercased before the check is ran.

Currently it seems to me that the only way is to manually specify that it is case insensitive with a pattern like `[Aa][Bb]12345\@mail\.com$`, but it would probably be better if you could apply this to exact blacklists and whitelists (non-pattern ones) to save on processing time and make the process a bit more straightforward and noob-proof.

**Comment by dizys** [comment]
Sorry for getting back to you late, was caught up with all my schoolwork.
Thank you, this is a very valid point. Please checkout version `1.0.6`, it should now be case insensitive on blacklists.
