### ISSUE TITLE
BUG: Type error

### ISSUE THREAD

**Issue by 226914011** [nyu8/flarum-email-filter#3]
#2 
Hi ,I'm new to here.
I've install the extension and this type error happens.
![圖片](https://user-images.githubusercontent.com/62089446/163999096-54feaaad-b083-47aa-87ae-d549174311c7.png)

Solution: 
Remove type prefix (array) for argument "$rules" in function checkRegex and checkLiteral
`
private static function checkLiteral(string $email, array $rules, bool $caseSensitive = false): bool
private static function checkRegex(string $email, array $rules, bool $caseSensitive = false): bool
`
to
`
private static function checkLiteral(string $email, $rules, bool $caseSensitive = false): bool
private static function checkRegex(string $email, $rules, bool $caseSensitive = false): bool
`

Correct me if I'm wrong, thanks

**Comment by dizys** [comment]
This is now fixed by v1.0.7.
Thank you!
